name: Build Preservation Python3 with Pygbag
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build-pygbag:
    name: Preservation-python3 Game
    runs-on: ubuntu-latest
    steps:
    - name: Checkout üõéÔ∏è
      uses: actions/checkout@v4

    - name: Compile translation files üà¥
      run: |
            echo "Attempting to install babel"
            python -m pip install babel
            echo "Successfully installed babel"
            echo "Compiling translation files"
            pybabel compile -d translations -D preservation
            echo "Successfully compiled translation files"

    - name: Install and Build üîß
      run: |
            echo "Attempting to install pygbag"
            python -m pip install pygbag
            echo "Successfully installed pygbag"
            echo "Attempting to build the game"
            python -m pygbag --build --template $GITHUB_WORKSPACE/default.tmpl $GITHUB_WORKSPACE/main.py
            echo "Successfully build the game and compiled to WebAssembly"

    - name: Upload to GitHub pages branch gh-pages üöÄ
      uses: JamesIves/github-pages-deploy-action@v4.7.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: gh-pages
        folder: build/web